AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  storageGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/get.handler
      Runtime: nodejs6.10
      Description: 'iLab-botのStorageからのget'
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::522354443334:role/ilab-bot-storage
      Environment:
        Variables:
            STORAGE_TABLE_NAME: ilab-bot-storage
  storageSet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/set.handler
      Runtime: nodejs6.10
      Description: 'iLab-botのStorageへのset'
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::522354443334:role/ilab-bot-storage
      Environment:
        Variables:
            STORAGE_TABLE_NAME: ilab-bot-storage
  storageUnset:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/unset.handler
      Runtime: nodejs6.10
      Description: 'iLab-botのStorageへのUnset'
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::522354443334:role/ilab-bot-storage
      Environment:
        Variables:
            STORAGE_TABLE_NAME: ilab-bot-storage